export const trips = [{
    hasInternationalFlights: true,
    outbound: {
      date: "Sat, 03 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "16:45",
      departureAirportCode: "JFK",
      arrivalTime: "07:15",
      arrivalAirportCode: "FCO",
      arrivalDayDifference: "",
      duration: "8h 30m",
      connectionsCount: 0,
      flights: [{
        airline: "British Airways",
        airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
        operatedBy: "American Airlines",
        departureTime: "16:45",
        departureAirportCode: "JFK",
        departureAirport: "JFK New York",
        departureLocation: 'New York, USA',
        arrivalTime: "07:15",
        arrivalAirportCode: "FCO",
        arrivalAirport: "Rome Fiumicino",
        arrivalLocation: 'Rome, ITA',
        flightNumber: "BA3249",
        duration: "13h 40m",
        cabinClass: 'Economy',
        connection: false,
        connectionTime: "2h 55m",
        connectionDetails: "Connect in Airport",
      }, ],
    },
    return: {
      date: "Thu, 21 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "12:25",
      departureAirportCode: "FCO",
      departureLocation: 'Rome, ITA',
      arrivalTime: "20:05",
      arrivalAirport: "JFK New York",
      arrivalAirportCode: "JFK",
      arrivalLocation: 'New York, USA',
      arrivalDayDifference: "+1",
      duration: "13h 40m",
      connectionsCount: 1,
      flights: [{
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "FCO",
          departureAirport: "Rome Fiumicino",
          departureLocation: 'Rome, ITA',
          arrivalTime: "07:15",
          arrivalAirportCode: "LGW",
          arrivalAirport: "London Gatwick",
          arrivalLocation: 'London, ENG',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: true,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
        {
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "LGW",
          departureAirport: "London Gatwick",
          departureLocation: 'London, ENG',
          arrivalTime: "07:15",
          arrivalAirportCode: "JFK",
          arrivalAirport: "JFK New York",
          arrivalLocation: 'New York, USA',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: false,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
      ],
    },
  },
  {
    hasInternationalFlights: true,
    outbound: {
      date: "Sat, 03 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "16:45",
      departureAirportCode: "JFK",
      arrivalTime: "07:15",
      arrivalAirportCode: "FCO",
      arrivalDayDifference: "",
      duration: "8h 30m",
      connectionsCount: 0,
      flights: [{
        airline: "British Airways",
        airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
        operatedBy: "American Airlines",
        departureTime: "16:45",
        departureAirportCode: "JFK",
        departureAirport: "JFK New York",
        departureLocation: 'New York, USA',
        arrivalTime: "07:15",
        arrivalAirportCode: "FCO",
        arrivalAirport: "Rome Fiumicino",
        arrivalLocation: 'Rome, ITA',
        flightNumber: "BA3249",
        duration: "13h 40m",
        cabinClass: 'Economy',
        connection: false,
        connectionTime: "2h 55m",
        connectionDetails: "Connect in Airport",
      }, ],
    },
    return: {
      date: "Thu, 21 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "12:25",
      departureAirportCode: "FCO",
      departureLocation: 'Rome, ITA',
      arrivalTime: "20:05",
      arrivalAirport: "JFK New York",
      arrivalAirportCode: "JFK",
      arrivalLocation: 'New York, USA',
      arrivalDayDifference: "+1",
      duration: "13h 40m",
      connectionsCount: 1,
      flights: [{
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "FCO",
          departureAirport: "Rome Fiumicino",
          departureLocation: 'Rome, ITA',
          arrivalTime: "07:15",
          arrivalAirportCode: "LGW",
          arrivalAirport: "London Gatwick",
          arrivalLocation: 'London, ENG',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: true,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
        {
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "LGW",
          departureAirport: "London Gatwick",
          departureLocation: 'London, ENG',
          arrivalTime: "07:15",
          arrivalAirportCode: "JFK",
          arrivalAirport: "JFK New York",
          arrivalLocation: 'New York, USA',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: false,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
      ],
    },
  },
  {
    hasInternationalFlights: true,
    outbound: {
      date: "Sat, 03 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "16:45",
      departureAirportCode: "JFK",
      arrivalTime: "07:15",
      arrivalAirportCode: "FCO",
      arrivalDayDifference: "",
      duration: "8h 30m",
      connectionsCount: 0,
      flights: [{
        airline: "British Airways",
        airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
        operatedBy: "American Airlines",
        departureTime: "16:45",
        departureAirportCode: "JFK",
        departureAirport: "JFK New York",
        departureLocation: 'New York, USA',
        arrivalTime: "07:15",
        arrivalAirportCode: "FCO",
        arrivalAirport: "Rome Fiumicino",
        arrivalLocation: 'Rome, ITA',
        flightNumber: "BA3249",
        duration: "13h 40m",
        cabinClass: 'Economy',
        connection: false,
        connectionTime: "2h 55m",
        connectionDetails: "Connect in Airport",
      }, ],
    },
    return: {
      date: "Thu, 21 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "12:25",
      departureAirportCode: "FCO",
      departureLocation: 'Rome, ITA',
      arrivalTime: "20:05",
      arrivalAirport: "JFK New York",
      arrivalAirportCode: "JFK",
      arrivalLocation: 'New York, USA',
      arrivalDayDifference: "+1",
      duration: "13h 40m",
      connectionsCount: 1,
      flights: [{
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "FCO",
          departureAirport: "Rome Fiumicino",
          departureLocation: 'Rome, ITA',
          arrivalTime: "07:15",
          arrivalAirportCode: "LGW",
          arrivalAirport: "London Gatwick",
          arrivalLocation: 'London, ENG',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: true,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
        {
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "LGW",
          departureAirport: "London Gatwick",
          departureLocation: 'London, ENG',
          arrivalTime: "07:15",
          arrivalAirportCode: "JFK",
          arrivalAirport: "JFK New York",
          arrivalLocation: 'New York, USA',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: false,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
      ],
    },
  },
  {
    hasInternationalFlights: true,
    outbound: {
      date: "Sat, 03 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "16:45",
      departureAirportCode: "JFK",
      arrivalTime: "07:15",
      arrivalAirportCode: "FCO",
      arrivalDayDifference: "",
      duration: "8h 30m",
      connectionsCount: 0,
      flights: [{
        airline: "British Airways",
        airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
        operatedBy: "American Airlines",
        departureTime: "16:45",
        departureAirportCode: "JFK",
        departureAirport: "JFK New York",
        departureLocation: 'New York, USA',
        arrivalTime: "07:15",
        arrivalAirportCode: "FCO",
        arrivalAirport: "Rome Fiumicino",
        arrivalLocation: 'Rome, ITA',
        flightNumber: "BA3249",
        duration: "13h 40m",
        cabinClass: 'Economy',
        connection: false,
        connectionTime: "2h 55m",
        connectionDetails: "Connect in Airport",
      }, ],
    },
    return: {
      date: "Thu, 21 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "12:25",
      departureAirportCode: "FCO",
      departureLocation: 'Rome, ITA',
      arrivalTime: "20:05",
      arrivalAirport: "JFK New York",
      arrivalAirportCode: "JFK",
      arrivalLocation: 'New York, USA',
      arrivalDayDifference: "+1",
      duration: "13h 40m",
      connectionsCount: 1,
      flights: [{
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "FCO",
          departureAirport: "Rome Fiumicino",
          departureLocation: 'Rome, ITA',
          arrivalTime: "07:15",
          arrivalAirportCode: "LGW",
          arrivalAirport: "London Gatwick",
          arrivalLocation: 'London, ENG',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: true,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
        {
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "LGW",
          departureAirport: "London Gatwick",
          departureLocation: 'London, ENG',
          arrivalTime: "07:15",
          arrivalAirportCode: "JFK",
          arrivalAirport: "JFK New York",
          arrivalLocation: 'New York, USA',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: false,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
      ],
    },
  },
  {
    hasInternationalFlights: true,
    outbound: {
      date: "Sat, 03 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "16:45",
      departureAirportCode: "JFK",
      arrivalTime: "07:15",
      arrivalAirportCode: "FCO",
      arrivalDayDifference: "",
      duration: "8h 30m",
      connectionsCount: 0,
      flights: [{
        airline: "British Airways",
        airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
        operatedBy: "American Airlines",
        departureTime: "16:45",
        departureAirportCode: "JFK",
        departureAirport: "JFK New York",
        departureLocation: 'New York, USA',
        arrivalTime: "07:15",
        arrivalAirportCode: "FCO",
        arrivalAirport: "Rome Fiumicino",
        arrivalLocation: 'Rome, ITA',
        flightNumber: "BA3249",
        duration: "13h 40m",
        cabinClass: 'Economy',
        connection: false,
        connectionTime: "2h 55m",
        connectionDetails: "Connect in Airport",
      }, ],
    },
    return: {
      date: "Thu, 21 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "12:25",
      departureAirportCode: "FCO",
      departureLocation: 'Rome, ITA',
      arrivalTime: "20:05",
      arrivalAirport: "JFK New York",
      arrivalAirportCode: "JFK",
      arrivalLocation: 'New York, USA',
      arrivalDayDifference: "+1",
      duration: "13h 40m",
      connectionsCount: 1,
      flights: [{
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "FCO",
          departureAirport: "Rome Fiumicino",
          departureLocation: 'Rome, ITA',
          arrivalTime: "07:15",
          arrivalAirportCode: "LGW",
          arrivalAirport: "London Gatwick",
          arrivalLocation: 'London, ENG',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: true,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
        {
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "LGW",
          departureAirport: "London Gatwick",
          departureLocation: 'London, ENG',
          arrivalTime: "07:15",
          arrivalAirportCode: "JFK",
          arrivalAirport: "JFK New York",
          arrivalLocation: 'New York, USA',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: false,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
      ],
    },
  },
  {
    hasInternationalFlights: true,
    outbound: {
      date: "Sat, 03 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "16:45",
      departureAirportCode: "JFK",
      arrivalTime: "07:15",
      arrivalAirportCode: "FCO",
      arrivalDayDifference: "",
      duration: "8h 30m",
      connectionsCount: 0,
      flights: [{
        airline: "British Airways",
        airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
        operatedBy: "American Airlines",
        departureTime: "16:45",
        departureAirportCode: "JFK",
        departureAirport: "JFK New York",
        departureLocation: 'New York, USA',
        arrivalTime: "07:15",
        arrivalAirportCode: "FCO",
        arrivalAirport: "Rome Fiumicino",
        arrivalLocation: 'Rome, ITA',
        flightNumber: "BA3249",
        duration: "13h 40m",
        cabinClass: 'Economy',
        connection: false,
        connectionTime: "2h 55m",
        connectionDetails: "Connect in Airport",
      }, ],
    },
    return: {
      date: "Thu, 21 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "12:25",
      departureAirportCode: "FCO",
      departureLocation: 'Rome, ITA',
      arrivalTime: "20:05",
      arrivalAirport: "JFK New York",
      arrivalAirportCode: "JFK",
      arrivalLocation: 'New York, USA',
      arrivalDayDifference: "+1",
      duration: "13h 40m",
      connectionsCount: 1,
      flights: [{
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "FCO",
          departureAirport: "Rome Fiumicino",
          departureLocation: 'Rome, ITA',
          arrivalTime: "07:15",
          arrivalAirportCode: "LGW",
          arrivalAirport: "London Gatwick",
          arrivalLocation: 'London, ENG',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: true,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
        {
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "LGW",
          departureAirport: "London Gatwick",
          departureLocation: 'London, ENG',
          arrivalTime: "07:15",
          arrivalAirportCode: "JFK",
          arrivalAirport: "JFK New York",
          arrivalLocation: 'New York, USA',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: false,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
      ],
    },
  },
  {
    hasInternationalFlights: true,
    outbound: {
      date: "Sat, 03 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "16:45",
      departureAirportCode: "JFK",
      arrivalTime: "07:15",
      arrivalAirportCode: "FCO",
      arrivalDayDifference: "",
      duration: "8h 30m",
      connectionsCount: 0,
      flights: [{
        airline: "British Airways",
        airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
        operatedBy: "American Airlines",
        departureTime: "16:45",
        departureAirportCode: "JFK",
        departureAirport: "JFK New York",
        departureLocation: 'New York, USA',
        arrivalTime: "07:15",
        arrivalAirportCode: "FCO",
        arrivalAirport: "Rome Fiumicino",
        arrivalLocation: 'Rome, ITA',
        flightNumber: "BA3249",
        duration: "13h 40m",
        cabinClass: 'Economy',
        connection: false,
        connectionTime: "2h 55m",
        connectionDetails: "Connect in Airport",
      }, ],
    },
    return: {
      date: "Thu, 21 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "12:25",
      departureAirportCode: "FCO",
      departureLocation: 'Rome, ITA',
      arrivalTime: "20:05",
      arrivalAirport: "JFK New York",
      arrivalAirportCode: "JFK",
      arrivalLocation: 'New York, USA',
      arrivalDayDifference: "+1",
      duration: "13h 40m",
      connectionsCount: 1,
      flights: [{
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "FCO",
          departureAirport: "Rome Fiumicino",
          departureLocation: 'Rome, ITA',
          arrivalTime: "07:15",
          arrivalAirportCode: "LGW",
          arrivalAirport: "London Gatwick",
          arrivalLocation: 'London, ENG',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: true,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
        {
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "LGW",
          departureAirport: "London Gatwick",
          departureLocation: 'London, ENG',
          arrivalTime: "07:15",
          arrivalAirportCode: "JFK",
          arrivalAirport: "JFK New York",
          arrivalLocation: 'New York, USA',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: false,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
      ],
    },
  },
  {
    hasInternationalFlights: true,
    outbound: {
      date: "Sat, 03 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "16:45",
      departureAirportCode: "JFK",
      arrivalTime: "07:15",
      arrivalAirportCode: "FCO",
      arrivalDayDifference: "",
      duration: "8h 30m",
      connectionsCount: 0,
      flights: [{
        airline: "British Airways",
        airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
        operatedBy: "American Airlines",
        departureTime: "16:45",
        departureAirportCode: "JFK",
        departureAirport: "JFK New York",
        departureLocation: 'New York, USA',
        arrivalTime: "07:15",
        arrivalAirportCode: "FCO",
        arrivalAirport: "Rome Fiumicino",
        arrivalLocation: 'Rome, ITA',
        flightNumber: "BA3249",
        duration: "13h 40m",
        cabinClass: 'Economy',
        connection: false,
        connectionTime: "2h 55m",
        connectionDetails: "Connect in Airport",
      }, ],
    },
    return: {
      date: "Thu, 21 Oct",
      airline: "British Airways",
      airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
      operatedBy: "American Airlines",
      departureTime: "12:25",
      departureAirportCode: "FCO",
      departureLocation: 'Rome, ITA',
      arrivalTime: "20:05",
      arrivalAirport: "JFK New York",
      arrivalAirportCode: "JFK",
      arrivalLocation: 'New York, USA',
      arrivalDayDifference: "+1",
      duration: "13h 40m",
      connectionsCount: 1,
      flights: [{
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "FCO",
          departureAirport: "Rome Fiumicino",
          departureLocation: 'Rome, ITA',
          arrivalTime: "07:15",
          arrivalAirportCode: "LGW",
          arrivalAirport: "London Gatwick",
          arrivalLocation: 'London, ENG',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: true,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
        {
          airline: "British Airways",
          airlineLogoUrl: "https://cdn.iconscout.com/icon/free/png-512/british-airways-2-569383.png",
          operatedBy: "American Airlines",
          departureTime: "16:45",
          departureAirportCode: "LGW",
          departureAirport: "London Gatwick",
          departureLocation: 'London, ENG',
          arrivalTime: "07:15",
          arrivalAirportCode: "JFK",
          arrivalAirport: "JFK New York",
          arrivalLocation: 'New York, USA',
          flightNumber: "BA3249",
          duration: "13h 40m",
          cabinClass: 'Economy',
          connection: false,
          connectionTime: "2h 55m",
          connectionDetails: "Connect in Airport",
        },
      ],
    },
  }
]